//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetduinoApplication6
{
    
    internal partial class Markup
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Markup.manager == null))
                {
                    Markup.manager = new System.Resources.ResourceManager("NetduinoApplication6.Markup", typeof(Markup).Assembly);
                }
                return Markup.manager;
            }
        }
        internal static string GetString(Markup.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            Html = 21347,
        }
    }
}
